//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P13ContactUsForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P13ContactUsForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form {
        ///    background: #eee;
        ///    display: inline-block;
        ///    width: 300px;
        ///}
        ///
        ///form span {
        ///    background: #eee;
        ///    width: 80px;
        ///    display: inline-block;
        ///    margin: 10px 3px 3px 8px;
        ///}
        ///
        ///form &gt; input, form &gt; select {
        ///    width: 150px;
        ///    height: 20px;
        ///    margin: 0 5px;
        ///    box-sizing: border-box;
        ///}
        ///
        ///form &gt; select {
        ///    margin: 1px 1px 1px 5px;
        ///}
        ///
        ///form &gt; input[type=&apos;submit&apos;] {
        ///    display: block;
        ///    margin: 10px 0 12px 100px;
        ///    width: 80px;
        ///    height: 30px;
        ///}.
        /// </summary>
        internal static string contact_us_form {
            get {
                return ResourceManager.GetString("contact_us_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type: text/html
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Contact Us&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;styles/contact-us-form.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Contact Us&lt;/h1&gt;
        ///    &lt;form&gt;
        ///        &lt;span&gt;First Name:&lt;/span&gt;
        ///        &lt;input type=&quot;text&quot; name=&quot;firstname&quot; /&gt;
        ///        &lt;span&gt;Last Name:&lt;/span&gt;
        ///        &lt;input type=&quot;text&quot; name=&quot;lastname&quot; /&gt;
        ///        &lt;span&gt;Email:&lt;/span&gt;
        ///        &lt;input type=&quot;text&quot; name=&quot;email&quot; /&gt;
        ///        &lt;span&gt;Town:&lt;/span&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
    }
}
