//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P07Fruits.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P07Fruits.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAXEAAAFxABGGER2wAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAJodJREFUeF7tnAd4VVXW928aKUDoiqJjY3SsiGUso2KZsY5jAZUqHaT3XiItEDohlEAooaVAEhLSSO+99x5CaEFqQAQirO+3LjcM+ur34aAOM9+7n+f/7HvO2Weftf57tX3uTQz/2661Lg4Gy16TDM+MGmWwNp3633a9icGs2zhD697jDJ16TzAf0meieWq/SeaBnzkYmphG/P/ThrgarMZ5GWwdVhhajltm6DDEwfCnfpMNL/eeaP5lnwlmTr3Hm0eDw30nWXz75UTLK19OtLjSd5J5L9Pt/53NwcFgvii8VYsle21fWOpvM3mRj806x922O+fvtAlxcG+SMcPNqnzKGq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppleBase64 {
            get {
                return ResourceManager.GetString("AppleBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAXEAAAFxABGGER2wAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAJAlJREFUeF7tfAecFcWWflfVTZMzYRiGnIYsSZKDzJBzVEAki0hSMSAGkqAEUUFEovhQwAQogpJBQHKOkgcEhjw5MPf22e9U38vAPvft292//9XH1u936Dtzu6urvj7nO9+p6sH4r7Z4w7DhEBQRYRl/vs8U7P8at3LlygUG+Pu/Yxhyr8Ol9vqHqL3KIfbiK7ZdsAZ83kPfwkuHB4WFh38QVdw/p3LzCE+1tqGeEtUDPK5Amycg1O4BgLdwWm3r7Ie4hcSGhDr81QehhZyZ9Z+OMh/pFEEFSvhRcJSLarQpREXLBxHAOsqnWlc8pC0EzS/I8WFwQUd6jQ4RZum6IRQZ60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BananaBase64 {
            get {
                return ResourceManager.GetString("BananaBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type: text/html
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Fruits&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Fruits&lt;/h1&gt;
        ///    &lt;p&gt;
        ///        &lt;img src=&quot;images/banana.png&quot; alt=&quot;banana&quot; /&gt;
        ///        &lt;img src=&quot;images/orange.png&quot; alt=&quot;orange&quot; /&gt;
        ///        &lt;img src=&quot;images/kiwi.png&quot; alt=&quot;kiwi&quot; /&gt;
        ///        &lt;img src=&quot;images/kiwi.png&quot; alt=&quot;kiwi&quot; /&gt;
        ///        &lt;img src=&quot;images/apple.png&quot; alt=&quot;apple&quot; /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;img src=&quot;images/apple.png&quot; alt=&quot;apple&quot; /&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuOWwzfk4AADlbSURBVHhe7Zx3VFVplva7Zmr66+mpaUvuJeccBclJggiKKCAqmEBBMWDOOWdRUck5KElQUTEhCBIEAbNixJxzzuH5nveovapq6Fo9M93fX1+ttdc5572B8/7us5+9N1zrD+3atfv/8XdGm4v/LyMmwPJPszqpuy8MUhkbPVwpJmaCfEvSXHlV2gLFI1nLFI9nLpbXZa+Qb0uYJY/dMEFxwsJ+6h6jbXX/0tZ7/bOjzcV/dgDtfojpa26xNEAnPnqk8rPEJXJkb5AhN0EBuYkK2JKlgJ25CtiVz2Nee+zY1B5bMr9GUXp7ZKxS+JQwW167eqTilC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KiwiBase64 {
            get {
                return ResourceManager.GetString("KiwiBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAXEAAAFxABGGER2wAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC45bDN+TgAAJ7FJREFUeF7NnHmcXUWZ/mdcRv2NToGAIZgQQkBERRxIiDGBAAHZBkGFCCPggguyiaDsIkEUE/ZdQEAQUFxQBBe2sGXpdNL7dnvvTneSTtJJZ+9s3fX7fuv2gU5yUUBmxj/ez7m37r3nVD31vM/7VJ3T/S8hhP/TiDH+axaFPv9nioKN/1PR1vbIu2LHAzvE9ismxapjjoq5L0yLzZc/FXMnPxdzRz8cm085NS6a9unYde/I2Hrxu//ZACzY+FZGjPe+I7bfMyrmzj49dlz3h9h5dW1sOa8foGKc+9EYK8bHOGf3GKsPjLH97BgX3dAPmPNj25kAeNal8akxx/feGHZbem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrangeBase64 {
            get {
                return ResourceManager.GetString("OrangeBase64", resourceCulture);
            }
        }
    }
}
